site_name: Triple j9
site_description: The jjj999's homepage.
site_url: https://github.com/jjj999

docs_dir: src
copyright: Copyright &copy; 2021 Yunhyeon Jeong

theme:
  name: material
  logo: res/elephant.jpg
  favicon: res/elephant.jpg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
  language: ja
  palette:
    primary: blue grey
  font:
    text: Merriweather

nav:
- index.md
- Blog: blog/index.md
- Projects: projects.md
- Researches: researches/index.md
- About: about.md

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  alternate:
    - name: 日本語
      link: /
      lang: ja
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:jjj999to@gmail.com
      name: Contact with jjj999
    - icon: fontawesome/brands/github
      link: https://github.com/jjj999/
      name: jjj999's Github account

plugins:
  - search
